/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCronogramasRouteImport } from './routes/_authenticated/cronogramas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProjetosIndexRouteImport } from './routes/_authenticated/projetos.index'
import { Route as AuthenticatedCronogramasIndexRouteImport } from './routes/_authenticated/cronogramas.index'
import { Route as AuthenticatedProjetosIdRouteImport } from './routes/_authenticated/projetos.$id'
import { Route as AuthenticatedCronogramasGeracaoIdRouteImport } from './routes/_authenticated/cronogramas.$geracaoId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCronogramasRoute =
  AuthenticatedCronogramasRouteImport.update({
    id: '/cronogramas',
    path: '/cronogramas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetosIndexRoute =
  AuthenticatedProjetosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjetosRoute,
  } as any)
const AuthenticatedCronogramasIndexRoute =
  AuthenticatedCronogramasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCronogramasRoute,
  } as any)
const AuthenticatedProjetosIdRoute = AuthenticatedProjetosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjetosRoute,
} as any)
const AuthenticatedCronogramasGeracaoIdRoute =
  AuthenticatedCronogramasGeracaoIdRouteImport.update({
    id: '/$geracaoId',
    path: '/$geracaoId',
    getParentRoute: () => AuthenticatedCronogramasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cronogramas': typeof AuthenticatedCronogramasRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/projetos': typeof AuthenticatedProjetosRouteWithChildren
  '/cronogramas/$geracaoId': typeof AuthenticatedCronogramasGeracaoIdRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/cronogramas/': typeof AuthenticatedCronogramasIndexRoute
  '/projetos/': typeof AuthenticatedProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/cronogramas/$geracaoId': typeof AuthenticatedCronogramasGeracaoIdRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/cronogramas': typeof AuthenticatedCronogramasIndexRoute
  '/projetos': typeof AuthenticatedProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/cronogramas': typeof AuthenticatedCronogramasRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRouteWithChildren
  '/_authenticated/cronogramas/$geracaoId': typeof AuthenticatedCronogramasGeracaoIdRoute
  '/_authenticated/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/_authenticated/cronogramas/': typeof AuthenticatedCronogramasIndexRoute
  '/_authenticated/projetos/': typeof AuthenticatedProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/configuracoes'
    | '/cronogramas'
    | '/dashboard'
    | '/empresas'
    | '/historico'
    | '/projetos'
    | '/cronogramas/$geracaoId'
    | '/projetos/$id'
    | '/cronogramas/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/historico'
    | '/cronogramas/$geracaoId'
    | '/projetos/$id'
    | '/cronogramas'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/configuracoes'
    | '/_authenticated/cronogramas'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/historico'
    | '/_authenticated/projetos'
    | '/_authenticated/cronogramas/$geracaoId'
    | '/_authenticated/projetos/$id'
    | '/_authenticated/cronogramas/'
    | '/_authenticated/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cronogramas': {
      id: '/_authenticated/cronogramas'
      path: '/cronogramas'
      fullPath: '/cronogramas'
      preLoaderRoute: typeof AuthenticatedCronogramasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/': {
      id: '/_authenticated/projetos/'
      path: '/'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AuthenticatedProjetosIndexRouteImport
      parentRoute: typeof AuthenticatedProjetosRoute
    }
    '/_authenticated/cronogramas/': {
      id: '/_authenticated/cronogramas/'
      path: '/'
      fullPath: '/cronogramas/'
      preLoaderRoute: typeof AuthenticatedCronogramasIndexRouteImport
      parentRoute: typeof AuthenticatedCronogramasRoute
    }
    '/_authenticated/projetos/$id': {
      id: '/_authenticated/projetos/$id'
      path: '/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof AuthenticatedProjetosIdRouteImport
      parentRoute: typeof AuthenticatedProjetosRoute
    }
    '/_authenticated/cronogramas/$geracaoId': {
      id: '/_authenticated/cronogramas/$geracaoId'
      path: '/$geracaoId'
      fullPath: '/cronogramas/$geracaoId'
      preLoaderRoute: typeof AuthenticatedCronogramasGeracaoIdRouteImport
      parentRoute: typeof AuthenticatedCronogramasRoute
    }
  }
}

interface AuthenticatedCronogramasRouteChildren {
  AuthenticatedCronogramasGeracaoIdRoute: typeof AuthenticatedCronogramasGeracaoIdRoute
  AuthenticatedCronogramasIndexRoute: typeof AuthenticatedCronogramasIndexRoute
}

const AuthenticatedCronogramasRouteChildren: AuthenticatedCronogramasRouteChildren =
  {
    AuthenticatedCronogramasGeracaoIdRoute:
      AuthenticatedCronogramasGeracaoIdRoute,
    AuthenticatedCronogramasIndexRoute: AuthenticatedCronogramasIndexRoute,
  }

const AuthenticatedCronogramasRouteWithChildren =
  AuthenticatedCronogramasRoute._addFileChildren(
    AuthenticatedCronogramasRouteChildren,
  )

interface AuthenticatedProjetosRouteChildren {
  AuthenticatedProjetosIdRoute: typeof AuthenticatedProjetosIdRoute
  AuthenticatedProjetosIndexRoute: typeof AuthenticatedProjetosIndexRoute
}

const AuthenticatedProjetosRouteChildren: AuthenticatedProjetosRouteChildren = {
  AuthenticatedProjetosIdRoute: AuthenticatedProjetosIdRoute,
  AuthenticatedProjetosIndexRoute: AuthenticatedProjetosIndexRoute,
}

const AuthenticatedProjetosRouteWithChildren =
  AuthenticatedProjetosRoute._addFileChildren(
    AuthenticatedProjetosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCronogramasRoute: typeof AuthenticatedCronogramasRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCronogramasRoute: AuthenticatedCronogramasRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
